### ISSUE TITLE
DBT Setup

### ISSUE THREAD

**Issue by yevgenybulochnik** [coderxio/sagerx#178]
# Problem Statement
What are the most critical data sources to redo in DBT for purdue
- [x] rxnorm_full
- [x] fda_ndc
- [ ] fda_excluded
- [ ] fda_unfinished
- [x] fda_enforcement

Optional:
- [x] nadac

# Criteria for Success
Convert these sources to use DBT

**Comment by jrlegrand** [comment]
FYI we've created a style guide (https://github.com/coderxio/sagerx/blob/main/docs/style_guide.md) and are working through dbt conversion for all of these. I think the only one left to go at this point is FDA enforcement reports.
