### ISSUE TITLE
ERROR: Service 'postgres' failed to build : Build failed

### ISSUE THREAD

**Issue by nghiencuuthuoc** [coderxio/sagerx#219]
Please help me!
I have error run on Ubuntu 22.04

rd@PharmApp:~/sagerx$ sudo docker-compose up airflow-init
WARNING: The UMLS_API variable is not set. Defaulting to a blank string.
Building postgres
[+] Building 0.1s (2/2) FINISHED                                 docker:default
 => [internal] load build definition from Dockerfile                       0.0s
 => => transferring dockerfile: 2B                                         0.0s
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 2B                                            0.0s
ERROR: failed to solve: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount4216261398/Dockerfile: no such file or directory
ERROR: Service 'postgres' failed to build : Build failed

Thanks
nghiencuuthuoc@gmail.com

**Comment by jrlegrand** [comment]
@nghiencuuthuoc - have you tried changing folder permissions?  Looks like the error is related to being able to read the dockerfile so thought folder permissions might have something to do with it.

From README:

> Troubleshooting
> If you get issues on folder permissions:
> 
> sudo chmod -R 777 postgres,data,extracts,logs,plugins

**Comment by jrlegrand** [comment]
@nghiencuuthuoc 

Or try the below:

> If you get trouble from the postgres container with errors such as password authentication failed for user "airflow" or role "airflow" does not exist, these are all from the same issue that postgres is not setting itself up correctly. This is because of a file permission issue solved by running chmod +x ./postgres/0_pg_stat_statement.sh. You might need to remove any existing database configuration with rm -rf airflow/data and docker-compose down --volumes.
