### ISSUE TITLE
New Database Schema Convention

### ISSUE THREAD

**Issue by lprzychodzien** [coderxio/sagerx#229]
# Proposal

## Schema Changes
- sagerx_lake - raw data from data sources and seed tables
- sagerx_dev - where mart tables in development live
- sagerx - where user-facing tables live 

## dbt table rules 
Based on dbt structure document [here](https://docs.getdbt.com/best-practices/how-we-structure/1-guide-overview)

- Only mart models are build, staging and intermediate tables are views 
- Mart models are be built from either staging or intermediate tables

- staging models 
  - use case: basic formatting and transformations 
  - naming: stg_[source]__[entity]s.sql
  
- intermediate models
  - use case: holds more complex business logic, more transformations, and some joins
  - naming: int_[entity]s_[verb]s.sql
  
- mart models
  - use case: final tables to be exposed to users, final joins and business logic can exist here
  - naming: [concept].sql

# Rationale

Schema better aligns with what users expect allowing for them to more easily find tables of interest and create their own in the future. 

dbt table rules allows us to align on when each type of model should be built

**Comment by jrlegrand** [comment]
FYI credit goes to @RiversPharmD for the initial thoughts on this issue.

**Comment by jrlegrand** [comment]
> Mart models are be built from either staging or intermediate tables

I think mart models could also use "datasource" tables from the "lake", right?  Or is staging the only model that should be accessing datasource directly?

**Comment by lprzychodzien** [comment]
I believe data sources are defined in the staging models. Therefore: 

- Data lake / datasource tables should only be accessed by staging models
- Marts should always depend on staging at minimum
- Staging and intermediate models supply marts

**Comment by jrlegrand** [comment]
Yeah after re-reading the dbt docs last night, I agree.

I was kind of confused about what the guide said about how to materialize intermediate tables.  They suggest either 1.) views in a [custom schema](https://docs.getdbt.com/docs/build/custom-schemas) or 2.) materialized [ephemerally](https://docs.getdbt.com/docs/build/materializations#ephemeral).  

Both of these seem kind of overly complicated for us at this point, but wanted to mention it.
