### ISSUE TITLE
Import Compounded Medication NDC  Information

### ISSUE THREAD

**Issue by lprzychodzien** [coderxio/sagerx#243]
# Problem Statement
Create DAG and DBT processes around Compounded Medication NDC  Information, importing it into SageRx 

[FDA Directory link](https://www.fda.gov/drugs/drug-approvals-and-databases/national-drug-code-directory)
[NDC compounded drugs database file (zip format)](https://www.accessdata.fda.gov/cder/compounders_ndc_directory.zip)

**Comment by jrlegrand** [comment]
Closing as we have this source documented in Notion.  https://coderx.io/sagerx/source-data/fda-compounded-drugs
