### ISSUE TITLE
Airflow Logging into Postgres

### ISSUE THREAD

**Issue by lprzychodzien** [coderxio/sagerx#251]
# Problem Statement
Add airflow logging so we can track data pull occurrences and issues

# Criteria for Success
Data available for easy dashboarding of data updates

**Comment by jrlegrand** [comment]
Should we just close https://github.com/coderxio/sagerx/issues/164 in favor of this issue you just created? I don't think the solution in #164 is necessarily exactly what we want to prescribe.

**Comment by lprzychodzien** [comment]
PR #281 implemented airflow config file which also set sql_alchemy_conn to correctly push all airflow logs into the postgres DB under the airflow database table public.log
