### ISSUE TITLE
Implement a cloud-hosted database

### ISSUE THREAD

**Issue by jrlegrand** [coderxio/sagerx#261]
# Proposal
Right now we "kind of" have a hosted database, but it's just a Docker container we have running a Postgres image hosted on Linode. It goes down occasionally and has 500 errors - likely due to nginx or something.

I'm not a DevOps guy or a DBA. We should discuss pros and cons of moving towards at least a cloud-hosted database.  It would have to be a Postgres database because otherwise we might have SQL issues - and also I just generally like Postgres.

# Rationale
A reliably hosted database should be a core offering of SageRx. This offloads a lot of the maintenance of that database, allowing us to focus on other aspects of the application.

Let's use this issue to discuss pros and cons.

**Comment by Bridg109** [comment]
Cons: Price and component networking. Ie we will need infrastructure to run
airflow as well (ideally python scraping is moved to lambda or equivalent
instead of in airflow).

Pros: scalability, what Joey said. Storage in cloud and ease to share
outputs.

**Comment by lprzychodzien** [comment]
Pros:
-  Consistent data access for interested parties. This ideally will allow us to offer superset access for people to play around with the data. 
- Logging changes in data from providers. 
- Running additional services to build out the ecosystem. 

Cons:
- Cost to run, setup, and maintain. 
- Migration cost if deciding to switch cloud providers.

**Comment by jrlegrand** [comment]
@RiversPharmD - could you look into some options for hosting a Postgres database and report back here?

**Comment by jrlegrand** [comment]
I'm exploring using supabase.  Some notes:

- Supabase seems to use "projects" that have one database called `postgres` in them
- You can manually add other databases with SQL
- Since we use a separate database for Airflow vs SageRx, I assume we would need two databases - not sure if this would mean two "projects" in supabase or manually adding a database to one "project" OR maybe just running the Airflow database locally / on an EC2 server and hosting the resulting SageRx data via supabase
- When I tried connecting SageRx's Airflow database to a supabase "project" database called "airflow", it was SOOOO SLOOWWWW - likely b/c the free-tier machine is really underpowered - but it was like impossibly slow so not sure if something else was going on
- When I tried running SageRx's Airflow via local Postgres database in Docker (as current state) but pointing SageRx at supabase for SageRx data, it was giving me a password incorrect error, even though the password works when connecting manually via Azure Data Studio

**Comment by jrlegrand** [comment]
With supabase, now the password isn't an issue for some reason, but I'm getting errors d/t the COPY function not being allowed.

```
[2024-03-27, 20:35:07 UTC] {standard_task_runner.py:105} ERROR - Failed to execute job 14 for task load_product (must be superuser or have privileges of the pg_read_server_files role to COPY from a file
HINT:  Anyone can COPY to stdout or from stdin. psql's \copy command also works for anyone.

```

**Comment by jrlegrand** [comment]
Holy crap I got at least one table in `sagerx_lake` and one table in `sagerx_dev` on supabase.

The stored Postgres function for ndc_to_11 (etc) needs to be re-written as a macro in dbt and the whole COPY permissions thing is a big deal that would prevent this from working if we can't figure it out...

![Image](https://github.com/coderxio/sagerx/assets/3269178/bc57156f-b624-4d00-b36e-5dac041d30c6)



![Image](https://github.com/coderxio/sagerx/assets/3269178/45b9732a-49ad-4366-a8e8-6fd341b5bc34)

**Comment by jrlegrand** [comment]
Maybe this?

https://supabase.com/docs/guides/database/tables#bulk-data-loading

**Comment by jrlegrand** [comment]
Digital Ocean has a PostgreSQL offering: https://docs.digitalocean.com/products/databases/postgresql/details/pricing/

**Comment by jrlegrand** [comment]
I think pg_hook's copy_expert function might be what we need to get around the lack of superuser for the COPY statement.

> `copy_expert(self, sql, filename, open=open)`
> [[source]](https://airflow.apache.org/docs/apache-airflow/1.10.3/_modules/airflow/hooks/postgres_hook.html#PostgresHook.copy_expert)
> Executes SQL using psycopg2 copy_expert method. Necessary to execute COPY command without access to a superuser.

https://airflow.apache.org/docs/apache-airflow/1.10.3/_api/airflow/hooks/postgres_hook/index.html#airflow.hooks.postgres_hook.PostgresHook.copy_expert

**Comment by jrlegrand** [comment]
Summary of issues I've already run into:
- Postgres stored functions ([converting to dbt macros](https://github.com/coderxio/sagerx/pull/272))
- Postgres COPY command [doesn't work without access to superuser](https://github.com/coderxio/sagerx/issues/261#issuecomment-2023938499) (pgsql /copy command replacement maybe or something totally different)
- Do we continue to put Airflow data in the same Postgres database as SageRx data? Or do we change that to sqlite (we will still need to host Airflow/dbt on a different machine)

**Comment by jrlegrand** [comment]
Meeting notes: https://www.notion.so/coderxio/Properly-hosted-SageRx-database-e84738b501c544b2839070d8acd70d3f?pvs=4

**Comment by jrlegrand** [comment]
Decision to move to BigQuery.  Will break this issue into several smaller issues.
