### ISSUE TITLE
Make dbt docs show up in BigQuery descriptions

### ISSUE THREAD

**Issue by jrlegrand** [coderxio/sagerx#295]
# Proposal
Do this: https://docs.getdbt.com/reference/resource-configs/persist_docs

# Rationale
Make it easy to work with descriptions in BigQuery without having to refer to dbt docs.

**Comment by jrlegrand** [comment]
@lprzychodzien - I think this was accomplished in your recent #299 PR right?

**Comment by lprzychodzien** [comment]
No that PR does not solve this.

**Comment by jrlegrand** [comment]
Note: persist_docs is turned on. It's just the way we are pushing data to BigQuery that is not making the persist_docs work as it normally does.

**Comment by jrlegrand** [comment]
BigQuery no longer a priority or focus.
