### ISSUE TITLE
Excipients with no matching FDA UNII code in data

### ISSUE THREAD

**Issue by joeschmoey** [coderxio/sagerx#297]
# Problem Statement
30-someting out of 17k+ excipients / inactive ingredients / substances in our data mart have UNII codes but did not map to most recent UNII data.  

Will the next UNII data load solve this? Or is there a different reason for this?

One thing I noticed is that if you search for these on the UNII website, they show up as a match, but only because they matched a synonym / mapping code... the code detail page you land on is for a different UNII.  So maybe some of these need to be mapped to more recent/updated/reused codes?
![image](https://github.com/coderxio/sagerx/assets/3584869/74b321c8-e859-43c8-9270-194017e3e83e)

# Criteria for Success
We reduce the number of unmatched UNII display names or show that they get resolved every time there is a new UNII data load.

# Additional Information
Investigate the mapping thing first.

Should also look into the NOCODE excipients and see if there's anything we can do about those.

**Comment by jrlegrand** [comment]
Duplicate / in error
