### ISSUE TITLE
Postgres Flat file Volume permissions

### ISSUE THREAD

**Issue by yevgenybulochnik** [coderxio/sagerx#44]
# Problem Statement
Currently we are binding a volume in the postgres container for flat file creation. This volume is created using the airflow-init command and has permissions set with `chmod o+rw`. We should explore adjusting this to have more specific permissions.

# Criteria for Success
Potentially set UID:GID in the postgres container, but need to explore this issue further

# Additional Information
[Random Reference](https://www.cbtnuggets.com/blog/technology/system-admin/when-to-use-chmod-vs-chown)

**Comment by jrlegrand** [comment]
We're not really creating "flatfiles" at the moment with SageRx. We're more creating dbt "marts" IMO and eventually we may create an Airflow DAG that grabs certain marts, converts them to flatfiles and sends those flatfiles to a s3 bucket or something. So I think this issue is obsolete.
