### ISSUE TITLE
SQL sorter (selection method)

### ISSUE THREAD

**Issue by Bridg109** [coderxio/sagerx#6]
# Proposal
Build a function to sort SQL statements based on table dependency. This should use objects to manage sql data.

# Rationale
This should be used to simplify the code in dynamic dag. It will easy the development of future data sets by handling the sql run order instead of devs managing this.

**Comment by jrlegrand** [comment]
I think this is an old issue that we could deal with in a variety of different ways if it comes up again now that we know more.  I.e. create a task hierarchy - or we may end up using dbt to create the empty table structure eventually.
