### ISSUE TITLE
CMS MUE files

### ISSUE THREAD

**Issue by Bridg109** [coderxio/sagerx#73]
# Proposal
Digest CMS MUE files. Store historical context for historical assessment

# Rationale
MUE determine drug administration limits for Medicare part b plans. These can be used to quickly review and assess drug admins for payments

**Comment by jrlegrand** [comment]
Closing as this is tracked in Notion: https://coderx.io/sagerx/source-data/source-data/medicare-ncci-medically-unlikely-edits-mues
