### ISSUE TITLE
CMS alpha Numeric HCPCS annual file

### ISSUE THREAD

**Issue by Bridg109** [coderxio/sagerx#75]
# Proposal
Digest the alpha numeric HCPCS annual file. Contains better descriptions of HCPCS codes

# Rationale
Can help with change files and has better descriptions of HCPCS codes

https://www.cms.gov/Medicare/Coding/HCPCSReleaseCodeSets/Alpha-Numeric-HCPCS

**Comment by jrlegrand** [comment]
Closing as this is tracked in Notion: https://coderx.io/sagerx/source-data/cms-alpha-numeric-hcpcs
