### ISSUE TITLE
Get FDA UNII data file

### ISSUE THREAD

**Issue by Bridg109** [coderxio/sagerx#80]
# Proposal
Review and download these datasets 
https://precision.fda.gov/uniisearch/archive

# Rationale
Help with normalizing inactive ingredient UNII codes. There is more extensive cross UNII mapping here.

**Comment by jrlegrand** [comment]
Closing as this is tracked in Notion: https://coderx.io/sagerx/source-data/source-data/fda-unique-ingredient-identifiers-uniis
