### ISSUE TITLE
Trigger DAG / Task based on completion of two different DAGs / Tasks

### ISSUE THREAD

**Issue by jrlegrand** [coderxio/sagerx#93]
# Problem Statement
In situations where we want to create a table or view view that combines two data sources, we need to know if and when both of those data sources complete updating.  They could either be completely missing, or recently updated.  We need a way to trigger the creation of that table or view only when the dependent tables exist, and in the case of creating a table, we want to re-create that table every time the dependent data sources are updated.

# Criteria for Success
For a view, it is only created when both dependent data sources exist.
For a table, it is only created when both dependent data sources exist, and it is automatically updated after any of its dependent data sources are updated.

# Additional Information
👉 This looks helpful: https://airflow.apache.org/docs/apache-airflow/stable/howto/operator/external_task_sensor.html

This is the closest thing I've found to a clue for this: https://airflow.apache.org/docs/apache-airflow/stable/concepts/dags.html#dag-dependencies

**ExternalTaskSensor**
https://airflow.apache.org/docs/apache-airflow/stable/_api/airflow/sensors/external_task/index.html?highlight=externaltasksensor#airflow.sensors.external_task.ExternalTaskSensor

**TriggerDagRunOperator**
https://airflow.apache.org/docs/apache-airflow/stable/_api/airflow/operators/trigger_dagrun/index.html#airflow.operators.trigger_dagrun.TriggerDagRunOperator

**Comment by lprzychodzien** [comment]
Recently commented on a similar issue here: https://github.com/coderxio/sagerx/issues/249
